### ISSUE TITLE
Option for loading images

### ISSUE THREAD

**Issue by mcrmonkey** [pjuu/pjuu#90]
Some users may not wish to load images by default on their timeline.

We should give users an option to alter this behaviour 

Options should be:

* Load posted images automatically 
* Let me load images by clicking a link

This option may be beneficial for users with a lower bandwidth ( mobile users for example )

**Comment by pjuu** [comment]
Like it :+1:

We could just highlight in the place of the image on a feed that there is one and then when they enter the post they will see the image.

**Comment by pjuu** [comment]
@mcrmonkey Can you please confirm the options because they are to complex.

The image should load when looking at an individual post no matter what otherwise a user will not get what is said in the correct context.

To that extend I propose an option "Don't load images on feed".

This will replace images on your feed, a user post list with a link saying there is an image. It will then be displayed when a user enters that post.

**Comment by mcrmonkey** [comment]
yeah sounds about right

maybe be worth looking in to 3 options then:

* click to load all images
* Load images while viewing posts
* always load images


Probably worth asking users what they would like maybe

**Comment by pjuu** [comment]
Ahhh... I see the issue the comments can also have images. I was thinking about the main posts contents which I think should always show the image if for example you are `/joe/<post_id>`.

The ones in the comments is a good point though. We can class that as a `feed` though. As clicking the image in a comment takes you no where except to the image itself which could get annoying as we don't allow genstures.

Will pop this on the site.

**Comment by docapotamus** [comment]
In master from above PR.
